### PR TITLE
Refactor all `global` references to util.global

### PR DESCRIPTION
**Pull request by benjamingr**
Fixes https://github.com/petkaantonov/bluebird/issues/988

### CODE REVIEW

**Comment by benjamingr** [comment]
All tests pass except the using.js tests for some reason @_@ I think it's not relevant though.

**Comment by petkaantonov** [comment]
Landed in 3.3

**Comment by sajjan56** [comment]
f75a84fed8249137

**Comment by sajjan56** [comment]
Gpg ke update

**Pull request closed without merging**
