### PR TITLE
Added Promise return value to Promise.config

### PR DESCRIPTION
**Pull request by artemjackson**
Implementation for #1223

### CODE REVIEW

**Comment by petkaantonov** [comment]
Can you also update the docs to reflect this change

**Comment by artemjackson** [comment]
@petkaantonov Yes, sure

**Comment by petkaantonov** [comment]
`Promise` means it returns a promise instance. `Object` is consistent with http://bluebirdjs.com/docs/api/promise.getnewlibrarycopy.html

**Comment by artemjackson** [comment]
My apolagies, now I see the difference

**Comment by artemjackson** [comment]
I reopened this PR but with another branch name to correspond to the changes

**Pull request closed without merging**
