### PR TITLE
Few minor grammar and formatting changes

### PR DESCRIPTION
**Pull request by thefourtheye**
I included a reference to [deferred anti-pattern](https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-deferred-anti-pattern) page as well.

### CODE REVIEW

**Comment by benjamingr** [comment]
Thanks! It would be really useful if you could go through the docs in the 3.0docs branch and give feedback/pr on those they're currently being written and will likely be the only reference very soon.

https://github.com/petkaantonov/bluebird/tree/3.0docs/docs/docs

PRs and help as well as criticism/opinions highly appreciated.

**Comment by thefourtheye** [comment]
@benjamingr Sure, I ll go through them whenever I find time :-)

**Comment by petkaantonov** [comment]
The deferred anti-pattern page will be renamed to "explicit construction anti-pattern". The anti-pattern was never specific to deferreds and applies to `new Promise` as well.

**Comment by benjamingr** [comment]
In SO we solved this by having "the promise constructor anti-pattern"
redirect to "the deferred anti pattern"

**Comment by thefourtheye** [comment]
@petkaantonov oh okay. Shall I remove that reference for now and add it back when the other page is ready?

**Comment by petkaantonov** [comment]
I mean I don't think the anti-pattern is related to the paragraph at all - if you're exercising the anti-pattern then changing deferred to new Promise doesn't really change anything.

**Comment by thefourtheye** [comment]
@petkaantonov Sure, I removed it now.

**Pull request merged**
