### PR TITLE
Promise.suppressRunawayWarning()

### PR DESCRIPTION
**Pull request by ben-page**
This is a proposed solution to the issue discussed here: #1059

### CODE REVIEW

**Comment by ben-page** [comment]
The reason I didn't use done():

The existing IS_FINAL flag didn't seem to be sufficient, because it's set on the new Promise created by done() not on the runaway promise. Since I had to create a new flag, it seems more clear to create `suppressRunawayWarning()` than to muddle the affect of calling `done()`. Additionally, usage of `done()` is pretty widely discouraged online and in the docs.

**Comment by petkaantonov** [comment]
Code LGTM, can you add documentation page and link in api reference?

**Comment by ben-page** [comment]
@petkaantonov, sorry for the delay. I added the docs you requested and rebased on master.

**Comment by spion** [comment]
Are there any test cases that test it?

**Comment by chung-leong** [comment]
Any chance this will get merged? The inability to do this is leading to a lot of spurious warnings in my React.js code. The following happens fairly frequently

`
return fetch().then((value) => {
    this.setState({ foo: value });
});
`
That sets component's state variable foo and trigger a rerender. The render request can be queued or happen immediately. If it's the latter case, and one of the React lifecycle function creates a promise chain, then the warning shows up--utterly unhelpful since it's not possible to link the two chains. The fact that it doesn't always happen makes it extra frustrating. 

Personally, I'd perfer something along the line of `Promise.isolate(() => { ... })` but I guess `Promise.try(() => { ... }).suppressRunawayWarning()` is pretty obvious too.

**Pull request closed without merging**
