### PR TITLE
Add neo-async to benchmark

### PR DESCRIPTION
**Pull request by suguru03**
I have developed  [Neo-Async](https://github.com/suguru03/neo-async).
I would appreciate if you could add it to benchmark list.

### CODE REVIEW

**Comment by petkaantonov** [comment]
I don't want to endorse this library as it currently is as it appears to make blatantly false claims.

> I rewrote it and removed codes like setImmediate to boost the performance, so the detail logic may differ from Async.

That's not a valid optimization because it obviously changes observable functionality. So it's not a drop-in replacement for async. What you may think is detail logic is [actually an important feature for many](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony).

**Comment by suguru03** [comment]
I apologize for my wrong claim and the delay.
I fixed source code and closed [this issue](https://github.com/suguru03/neo-async/issues/6).
Could you please check again this PR?

**Comment by petkaantonov** [comment]
Nice, thank you for that. Landed in https://github.com/petkaantonov/bluebird/commit/3d0a2cbe37809e338d24f433839bd900e1d8f86e

**Comment by suguru03** [comment]
Thank you so much.

**Pull request closed without merging**
