### PR TITLE
Promise.coroutine should respect the arity of the generator

### PR DESCRIPTION
**Pull request by renegare**
#927

### CODE REVIEW

**Comment by benjamingr** [comment]
What's the behavior of this on old IE?

**Comment by petkaantonov** [comment]
on IE arity will be 0

**Comment by benjamingr** [comment]
@renegare why the mocha test changes? Also, can you please add some tests to this?

**Comment by spion** [comment]
@benjamingr looks like a test has already been added. Are there any browser obstacles to merging this?

**Comment by renegare** [comment]
@all happy new year and all that jazz ... been awol but back.

@benjamingr ... old IE ... do they even support generators?

@petkaantonov  could you suggest a better place to put tests? i presummed ```test/mocha/generator.js``` is for testing the usage of generators. no?

@spion I have not taken a look, I'm on osx. Is this a manual process to verify in IE (and all other browsers) or is there a more simpler way to do so?

Apologies on the slowness of getting back. If you can give me clearer direction or someone would like take this over, feel free :)

**Comment by benjamingr** [comment]
> old IE ... do they even support generators?

Only through regenerator and similar tools. I was just concerned this would not break things there. Testing it - it looks fine. 

> .. could you suggest a better place to put tests? i presummed test/mocha/generator.js is for testing the usage of generators. no?

I would add two/three tests for different scenarios (function with lots of arguments, function without arguments, etc). 

Happy new year.

**Comment by renegare** [comment]
Cool fair enough, I'll update the tests and run through some manual tests and report back.

as for regenerator, do you have a link to this? sounds interesting ... I've only recently come to appreciate gens #noO0b

**Comment by renegare** [comment]
found it: https://github.com/facebook/regenerator

is it me or do we refuse to let old IEs die ...?

**Comment by benjamingr** [comment]
@renegare we build things so people use them - if people still use older versions of IE, we have nothing to do about it except if we're willing to lose money for it.

**Comment by renegare** [comment]
@benjamingr I'm not being paid to do this ...;) but hey its just a thought ...

... the next es7,8,9 more polyfills to keep old IEs on board ...

... then again you may be right about money. It does keep me in a job.

**Comment by petkaantonov** [comment]
Merged in 3.1.2

**Comment by renegare** [comment]
Thanks guys.

**Pull request closed without merging**
