### PR TITLE
added proper version check supporting VSCode

### PR DESCRIPTION
**Pull request by mlostekk**
added a version check for the `process`.

This adds support for the debugger running inside VSCode.

### CODE REVIEW

**Comment by benjamingr** [comment]
@petkaantonov we need a release, it might also be a good time to fix the TS issue @spion looked into.

**Comment by benjamingr** [comment]
@mlostekk petka needs to release - this requires him to run a script - can take a few days I guess

**Comment by mlostekk** [comment]
okay great. cant wait :)

**Comment by mlostekk** [comment]
@petkaantonov is there an ETA?

**Comment by benjamingr** [comment]
@petkaantonov

**Comment by mlostekk** [comment]
dont want to bother you too much, but any ETA @petkaantonov?

**Comment by mlostekk** [comment]
mh, is this repo still maintained?

**Comment by benjamingr** [comment]
@mlostekk yes, but changes happen pretty infrequently because of stability mostly. Let's try another @petkaantonov

**Comment by petkaantonov** [comment]
ok ill do release soon

**Comment by petkaantonov** [comment]
released 3.5.4

**Pull request merged**
