### PR TITLE
[docs] contradiction

### PR DESCRIPTION
**Pull request by timruffles**
this was confusing

### CODE REVIEW

**Comment by benjamingr** [comment]
Thanks!

**Comment by petkaantonov** [comment]
? this changes the meaning

**Comment by benjamingr** [comment]
@petkaantonov yes, but why would you want to switch to a library that doesn't expose prototypes? 

The old meaning made no sense (at least from your PoV)

**Comment by petkaantonov** [comment]
the todo is for the docs that are currently using fake example but should use a realistic one instead

**Comment by benjamingr** [comment]
@petkaantonov it looked like a really opinionated TODO on what the user reading the docs should do and not a TODO for the docs themselves - as if you were suggesting replacing the library people were using with a bad one.

**Pull request closed without merging**
