### PR TITLE
FIXES #1000

### LINKED ISSUE #1000: Promise.delay will not clearTimeout when cancelled
Using `bluebird 3.2.2` 
Similar to  #926 with `timeout` When canceling a `Promise.delay` the internally used timeout is not cleared and the process will hang

```javascript
var Promise = require('bluebird');
Promise.config({cancellation: true});

process.on('exit', function() {
  console.log(new Date(), 'Process exiting');
});

console.log(new Date(), 'Starting');
var delayPromise = Promise.delay(10000);

delayPromise.finally(function () {
	if (delayPromise.isCancelled()) {
		console.log(new Date(), 'Cancelled');
	}
});

setTimeout(function() {
	console.log(new Date(), 'Cancelling promise');
	delayPromise.cancel();
}, 1000);
```
Output -
```
Tue Feb 09 2016 05:17:03 GMT+0000 (UTC) 'Starting'
Tue Feb 09 2016 05:17:04 GMT+0000 (UTC) 'Canceling promise'
Tue Feb 09 2016 05:17:04 GMT+0000 (UTC) 'Cancelled'
Tue Feb 09 2016 05:17:13 GMT+0000 (UTC) 'Process exiting'
```

Notice the 10 seconds delay between the promise being canceled and the process exiting

### PR DESCRIPTION
**Pull request by yonjah**
Add clearTimeout on delay cancel

### CODE REVIEW

**Comment by petkaantonov** [comment]
Thank you. The case where `value` is should be handled as well.

**Comment by yonjah** [comment]
I think it's OK now

**Comment by petkaantonov** [comment]
I don't understand how in the first case the timeout is cleared after cancel, it doesn't even refer to `handle`

**Comment by yonjah** [comment]
Do you mean, when delay is called with a value ?
The timeout isn't cleared in that case since it's not being set yet.
It will be set on the next call to delay (being made from `afterValue`) and in that case a onCancel handler is set as well.

**Comment by petkaantonov** [comment]
Landed in 3.3

**Pull request closed without merging**
