### PR TITLE
Fixed jshint complaints (interrupted testing)

### PR DESCRIPTION
**Pull request by Artazor**
Fixed line length check failure introduced in 9112e573111a1aa462147f146859b72d081738e9

### CODE REVIEW

**Comment by Artazor** [comment]
*Update:*   added two commits:

* 5dccd5b - to enable cancellation testing in browser.
* 29d9e5f - to make `awaitGlobalException` browser friendly (`process.on` and `process.off` emulated by th browserify was no-op)

**Comment by petkaantonov** [comment]
Thanks, can you rebase this to current 3.0?

**Comment by Artazor** [comment]
Done!

**Comment by Artazor** [comment]
Btw, have you checked why the Travis CI is failing - only the last variant (of four) is successful?

**Comment by petkaantonov** [comment]
PR builds don't have access to access tokens for sauce labs and 3.0 builds fail on certain node versions

**Comment by petkaantonov** [comment]
Landed in https://github.com/petkaantonov/bluebird/commit/0b2a2bbce8c168206a54406c68b9c3eb263590fe

**Pull request closed without merging**
