### PR TITLE
How about we kill the sync build from the docs?

### PR DESCRIPTION
**Pull request by benjamingr**
What do you think?

### CODE REVIEW

**Comment by spion** [comment]
:+1:

**Comment by petkaantonov** [comment]
The sync build doesn't exist in 3.0 and the docs make no reference it there.

**Comment by benjamingr** [comment]
@petkaantonov but these are the docs I checked out the 3.0 branch o_0?

**Comment by petkaantonov** [comment]
they will be deleted once website is ready

**Comment by YuriSolovyov** [comment]
There will be website ? O__o

**Pull request closed without merging**
