### PR TITLE
Fix error on improperly-invoked promisify callback

### PR DESCRIPTION
**Pull request by snowblindroan**
Prior discussion: https://github.com/petkaantonov/bluebird/pull/1016#issuecomment-188247268

### CODE REVIEW

**Comment by benjamingr** [comment]
LGTM

**Comment by petkaantonov** [comment]
But the user cannot do anything about this error... I think if there is no arguments then it should resolved with undefined? Or what is the intention of the callback when it calls with 0 arguments?

**Comment by benjamingr** [comment]
In 99% of cases it's probably people who promisified event emitters incorrectly.

**Comment by petkaantonov** [comment]
How would promisifying event emitter cause a callback to be called?

**Comment by benjamingr** [comment]
```
net.connectAsync().then(() => {
    
});
```

**Comment by petkaantonov** [comment]
`connectListener` is that really called with 0 arguments? isn't it called with socket?

**Comment by benjamingr** [comment]
That's a good point, I recall it was in the 0.8 happy days when I was still writing to raw tcp.

**Comment by wltsmrz** [comment]
I don't recall that it ever was. As far as I can tell the callback to `createConnection()` was introduced in [this commit](https://github.com/nodejs/node/commit/c60cdcda4e39081fa56568df941aff1a4b56b39c). There is [no argument](https://github.com/nodejs/node/blob/c60cdcda4e39081fa56568df941aff1a4b56b39c/lib/net_uv.js#L351-L359) to the callback

**Comment by benjamingr** [comment]
Oh yeah, I'm thinking about createServer my bad.

**Comment by benjamingr** [comment]
@petkaantonov why the close?

**Comment by petkaantonov** [comment]
Errback called with no arguments can also be a success, can't it?

**Comment by benjamingr** [comment]
Oh yeah, I've never seen this though.

**Pull request closed without merging**
