### PR TITLE
add api reference to the top bar

### PR DESCRIPTION
**Pull request by EtaiG**
I personally find the API docs very useful, and I think most people who come to bluebird will too.. it would be nice to have a link for it in the top bar :)

### CODE REVIEW

**Comment by benjamingr** [comment]
Sounds like a good idea to me, anyone objects?

**Comment by spion** [comment]
👍

**Comment by benjamingr** [comment]
Thanks, will be up on the next docs rebuild

**Comment by EtaiG** [comment]
Awesome! Thank you so much :) 👍

**Pull request merged**
