### PR TITLE
Add Swift language to coming-from-other-languages

### PR DESCRIPTION
**Pull request by AndrewBarba**
Add Swift language to coming-from-other-languages

### CODE REVIEW

**Comment by benjamingr** [comment]
This is not a "coming from", this is a link to your library :) add some coming from.

**Comment by AndrewBarba** [comment]
Hey you have to at least appreciate the effort :)

**Comment by benjamingr** [comment]
Are you going to work on this and add some content :)?

**Comment by AndrewBarba** [comment]
Yes! There's no less content here than the Objc section, but I want to wait for more feedback on the library so I can comment on things people actually like/use. It would make sense to bring up the features people are actually familiar with after all

**Comment by benjamingr** [comment]
Good luck with your library

**Pull request closed without merging**
