### PR TITLE
[DL] (WEB-5100) Memory leak in bluebird

### PR DESCRIPTION
**Pull request by davydog187**

### CODE REVIEW

**Comment by bergus** [comment]
What's the difference to #725?
Why did you immediately close this?
What memory leak does happen, is this already reported as a bug somewhere?

**Comment by davydog187** [comment]
It was a mistake. I created a private fork of bluebird and entered the PR twice to the wrong place.

This is actually a duplicate of #669 and #671 which was put in by a colleague of mine, but was closed. We are able to consistently reproduce the memory leak from within the context of our app, but have not been able to create a smaller example of this issue. I think the leak is not exposing itself in the smaller example in #669 due to not enough memory consumption.

**Comment by davydog187** [comment]
https://msdn.microsoft.com/en-us/library/bb250448(v=vs.85).aspx is relevant

**Comment by davydog187** [comment]
@bergus maybe we can reopen the conversation?

**Comment by benjamingr** [comment]
Reopen what conversaion? You closed the PR and deleted the branch.

**Comment by davydog187** [comment]
@benjamingr the conversation in #671

**Comment by benjamingr** [comment]
@davydog187 you guys didn't (and still haven't replied). If you have something to add we'd love to hear it and I'll reopen. It was closed for lack of input.

**Pull request closed without merging**
