### PR TITLE
disable mutation-observer scheduler in IE

### PR DESCRIPTION
**Pull request by davedoran**

### CODE REVIEW

**Comment by benjamingr** [comment]
@davedoran hey

**Comment by davedoran** [comment]
Yeah - sorry; didn't mean to submit this PR back to the main fork.

**Comment by benjamingr** [comment]
@davedoran ok - if I may ask - why was it required on your end?

(You can `setScheduler` by the way and avoid changing the source code)

**Comment by davedoran** [comment]
I develop a large application that is migrating from jQuery to BlueBird.  We're noticing that - on IE11 - the MutationObserver occasionally fails to trigger when it should. The result is (rarely) a serious performance impact on IE. We have seen delays in the range of minutes where the application is blocked waiting for the callback. 

Unfortunately, I don't have a reliable testcase outside of my application (hence - not submitting this patch) but falling back to `setTimeout` on IE sidesteps the issue. 

Thanks for the hint re: ```setScheduler```.  That will be very useful.

**Comment by benjamingr** [comment]
Thanks for the update, we'll look into it.

**Comment by davedoran** [comment]
Cool - thanks.  I suspect we're hitting the same issue discussed here: 

https://github.com/petkaantonov/bluebird/issues/1161
https://github.com/lowkay/MutationObserverSchedulerBug

**Pull request closed without merging**
