### PR TITLE
`!==` was used where a `===` is needed

### PR DESCRIPTION
**Pull request by JamesCropcho**

### CODE REVIEW

**Comment by benjamingr** [comment]
Thanks!

**Comment by JamesCropcho** [comment]
Hey, somehow we (inexplicably) have a failing build here.

Would love for this PR to be merged. Anything I can do to help?

**Comment by benjamingr** [comment]
I'm OOO, I'll merge it when I get home (can't merge from mobile) unless Gorgi or Petka see it first. 

Appreciated.

**Comment by spion** [comment]
Its just saucelabs not working, as usual. This is safe to merge.

**Pull request merged**
